[build-system]
requires = ["setuptools>=80.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "philosophy-rag-engine"
dynamic = ["version"]

requires-python = "<=3.12.7"

# macOS: brew install xz

authors = [
  {name = "Akshay Irudayaraj", email = "akshay.irudayaraj@gmail.com"}
]

description = "rag for philosophy"

[tool.setuptools]
py-modules = ["output", "shared_types"] # TODO: make it so this doesn't have to be manual

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]